asn: 65000
bgp_neighbors:
- neighbor: 10.0.1.1
  remote_as: 65001
  state: present
- neighbor: 10.0.1.3
  remote_as: 65001
  state: present
- neighbor: 10.0.1.5
  remote_as: 65002
  state: present
- neighbor: 10.0.1.7
  remote_as: 65002
  state: present
evpn_neighbors:
- neighbor: 10.0.250.11
  remote_as: 65001
  state: present
- neighbor: 10.0.250.12
  remote_as: 65001
  state: present
- neighbor: 10.0.250.13
  remote_as: 65002
  state: present
- neighbor: 10.0.250.14
  remote_as: 65002
  state: present
hostname: spine1
interfaces:
- address: 10.0.1.0
  description: leaf1
  interface: Ethernet1
  mask: /31
- address: 10.0.1.2
  description: leaf2
  interface: Ethernet2
  mask: /31
- address: 10.0.1.4
  description: leaf3
  interface: Ethernet3
  mask: /31
- address: 10.0.1.6
  description: leaf4
  interface: Ethernet4
  mask: /31
loopback0_ip: 10.0.250.1
